push 6 home work
Zxciscool/home_work_hillel pull request #3
Opened 2022-02-14 09:29 UTC by Zxciscool

Выполнил задание с карточками 

Сделал условную разбивку сайта на 3 части : header, Main и Footer 

В header у меня заголовок h1 и меню 
<img width="594" alt="header" src="https://user-images.githubusercontent.com/96772761/153835395-6ddfaf58-7512-4beb-bd29-18c1bb1d4621.png">

в main у меня 2 абзаца рыба текст + карточки 
<img width="663" alt="карточки" src="https://user-images.githubusercontent.com/96772761/153835545-9e9acedf-01bc-4ca5-8475-2cacdf98ef5c.PNG">

Footer я сделал 3 блока и с помощью display inline-block выставил их в один ряд.
Так же использовал на сайте цитату.
<img width="625" alt="футер" src="https://user-images.githubusercontent.com/96772761/153835760-54de116d-83e8-4bda-a1c9-8adceddfb8cd.PNG">

В навигационном меню я использовал свойство :hover, что бы окрасить меню при наведении курсора и для эстетики )
<img width="576" alt="Hover список" src="https://user-images.githubusercontent.com/96772761/153835887-2b677de5-bfe5-4373-94b5-c784a32d1094.png">

Карточки я сделал с помощью одного блока родителя и внутрь добавил еще 6 маленьких блока. С помощью Inline-block все выровнял. 
<img width="240" alt="карточка код" src="https://user-images.githubusercontent.com/96772761/153836087-607cef62-620b-4b88-ab83-e5b16cf33ac9.PNG">

По итогу 1 карточка имеет заголовок, картинку, цену, описание и кнопка "купить"
<img width="195" alt="карточка" src="https://user-images.githubusercontent.com/96772761/153836295-bea31fc2-b2d4-4126-abd4-17f2d684fcb8.PNG">

Для кнопки "купить" Использовал свойство :hover со свойством opacity (прозрачность)
<img width="576" alt="Hover карточка" src="https://user-images.githubusercontent.com/96772761/153836534-7e6b41ec-85bc-4017-b500-398b66d2f696.png">

Футер выполнен с 3 блоков + блок родителя. С помощью Display inline block выставил элементы в один ряд. 
<img width="270" alt="футер код" src="https://user-images.githubusercontent.com/96772761/153836762-c9195c0c-81fe-46cd-8b92-00b388c7bee9.PNG">

2022-02-15 13:11 UTC, fo0lman requested changes

2022-02-15 13:11 UTC, fo0lman commented on dz_6_golubov/index.html
> +    <link rel="stylesheet" href="./css/style.css">
лучше каталог назвать styles

2022-02-15 13:11 UTC, fo0lman commented on dz_6_golubov/index.html
> +                        <img src="./img/ведро железное.jpg" alt="ведро железное">
кириллица очень не хорошо

2022-02-15 13:11 UTC, fo0lman commented on dz_6_golubov/index.html
> +                        <img src="./img/набор .jpeg" alt="набор веник и совок">
тут ошибка

2022-02-15 13:11 UTC, fo0lman commented on dz_6_golubov/index.html
> +                        <img src="./img/набор .jpeg" alt="набор веник и совок">
в названии

2022-02-15 13:11 UTC, fo0lman commented on dz_6_golubov/index.html
> +                        <img src="./img/Набор веник.jpeg" alt="набор веник и совок">
и тут

2022-02-15 13:11 UTC, fo0lman commented on dz_6_golubov/index.html
> +</html>
отступы в конце файлов

2022-02-15 13:40 UTC, Zxciscool commented on dz_6_golubov/index.html
> +    <link rel="stylesheet" href="./css/style.css">
Поменял название 
<img width="317" alt="Стили" src="https://user-images.githubusercontent.com/96772761/154073390-bdc9237e-d5aa-4caa-a7f7-6792513f9373.PNG">

2022-02-15 13:40 UTC, Zxciscool commented on dz_6_golubov/index.html
> +                        <img src="./img/ведро железное.jpg" alt="ведро железное">
<img width="449" alt="Кирилица" src="https://user-images.githubusercontent.com/96772761/154073448-c0d53def-218f-420a-a789-1b4f8b6c285c.PNG">

2022-02-15 13:41 UTC, Zxciscool commented on dz_6_golubov/index.html
> +                        <img src="./img/набор .jpeg" alt="набор веник и совок">
Поменял название, убрал Кириллицу 
<img width="432" alt="Ошибка названия" src="https://user-images.githubusercontent.com/96772761/154073534-6b0949ba-8e5f-4531-a420-b9352634fe6a.PNG">

2022-02-15 13:42 UTC, Zxciscool commented on dz_6_golubov/index.html
> +                        <img src="./img/Набор веник.jpeg" alt="набор веник и совок">
Тут тоже подправил 
<img width="374" alt="Вторая_ошибка" src="https://user-images.githubusercontent.com/96772761/154073663-83d1d047-09ce-4ee8-be4e-8256d6e71b99.PNG">

2022-02-15 13:42 UTC, Zxciscool commented on dz_6_golubov/index.html
> +</html>
Добавил последнюю строчку 
<img width="443" alt="Отступ" src="https://user-images.githubusercontent.com/96772761/154073782-0721dfd6-b74d-483f-adf6-a8c85d4344df.PNG">

2022-02-15 13:44 UTC, Zxciscool commented
Внес все правки, как вы и просили. 
Сделал новый пуш

2022-02-16 09:17 UTC, sergey-yarchuk-4ib commented on dz_6_golubov/index.html
> +    <link rel="stylesheet" href="./css/style.css">
не файл - каталог
./styles/style.css

потом может быть
./styles/home.scss
./styles/about.less
./styles/file.sass

как видишь трабла не в файле  а вкаталоге

2022-02-16 09:19 UTC, fo0lman commented on dz_6_golubov/index.html
> +    <link rel="stylesheet" href="./css/style.css">
не файл - каталог
./styles/style.css

потом может быть
./styles/home.scss
./styles/about.less
./styles/file.sass

как видишь трабла не в файле а вкаталоге

2022-02-16 09:20 UTC, fo0lman approved these changes

2022-02-16 09:20 UTC, merged